dist: focal
language: ruby
cache: bundler

rvm:
  - 2.6
  - 2.7

jobs:
  exclude:
    - rvm: 2.6
      gemfile: gemfiles/rails_7.0.gemfile

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_7.0.gemfile

before_install:
  - gem update --system --force -N > /dev/null && echo "Rubygems version $(gem --version)" && bundle --version

script:
  - bundle exec rspec
